%% =========================================================
%   HABER-BOSCH REACTOR COOLING DUTY
%   Reactor is exothermic - heat must be removed to
%   maintain operating temperature (~500 C, 200 bar)
%   
%   Energy balance on reactor:
%   Q_removed = Q_reaction + Q_sensible_out - Q_sensible_in
%   
%   i.e. heat removed = heat generated by rxn
%                     + enthalpy carried out by products
%                     - enthalpy brought in by feed
% =========================================================
clc; clear;

%% ---- CONSTANTS -----------------------------------------
R = 0.008314;              % kJ/mol-K
dH_rxn_per_mol_NH3 = -46.2; % kJ/mol NH3 (exothermic)

%% ---- Cp/R POLYNOMIAL COEFFICIENTS ----------------------
% Cp/R = A + B*T + C*T^2 + D/T^2
coeffs_N2   = {3.280, 0.593E-3, 0, 0.040E+5};
coeffs_H2   = {3.249, 0.422E-3, 0, 0.083E+5};
coeffs_NH3g = {3.578, 3.020E-3, 0, -0.186E+5};

%% ---- FLOW RATES (kmol/day) ------------------------------
nN2_fresh        = 1470.5882;
nH2_fresh        = 4411.7646;
nN2_recycle      = 5882.3528;
nH2_recycle      = 17647.0584;
nNH3_recycle_liq = 154.7987;
nNH3_export      = 2941.1764;

%% ---- DERIVED FLOWS -------------------------------------
nNH3_produced    = nNH3_export + nNH3_recycle_liq;  % total NH3 made in reactor
xi               = nNH3_produced / 2;               % extent of reaction
nN2_in           = nN2_fresh + nN2_recycle;
nH2_in           = nH2_fresh + nH2_recycle;
nN2_out          = nN2_in  - xi;
nH2_out          = nH2_in  - 3*xi;
nNH3_out         = nNH3_produced;

%% ---- TEMPERATURES (K) ----------------------------------
T_in  = 773.15;   % K  (500 C - feed enters reactor preheated by A_H01)
T_out = 773.15;   % K  (500 C - assume isothermal reactor, conservative)
                  % If reactor outlet is hotter e.g. 550 C, change T_out

%% ---- REACTION HEAT -------------------------------------
Q_rxn = nNH3_produced * dH_rxn_per_mol_NH3;   % kJ/day (negative = exothermic)

%% ---- SENSIBLE HEAT: INLET STREAMS TO REACTOR ----------
% All streams already at 500 C entering reactor (preheated upstream)
% Sensible heat change across reactor (T_in -> T_out)
% If isothermal: dT = 0, sensible terms = 0
% Included here for completeness if T_in =/= T_out

Q_sens_N2_in  = nN2_in  * H_change(T_in, T_out, coeffs_N2{:},   R);
Q_sens_H2_in  = nH2_in  * H_change(T_in, T_out, coeffs_H2{:},   R);
Q_sens_NH3_in = nNH3_recycle_liq * H_change(T_in, T_out, coeffs_NH3g{:}, R);

%% ---- SENSIBLE HEAT: OUTLET STREAMS FROM REACTOR -------
Q_sens_N2_out  = nN2_out  * H_change(T_in, T_out, coeffs_N2{:},   R);
Q_sens_H2_out  = nH2_out  * H_change(T_in, T_out, coeffs_H2{:},   R);
Q_sens_NH3_out = nNH3_out * H_change(T_in, T_out, coeffs_NH3g{:}, R);

%% ---- REACTOR ENERGY BALANCE ----------------------------
% Q_removed = Q_rxn + (H_out - H_in)
% For isothermal: H_out - H_in = 0, so Q_removed = -Q_rxn

Q_sensible_net = (Q_sens_N2_out + Q_sens_H2_out + Q_sens_NH3_out) ...
               - (Q_sens_N2_in  + Q_sens_H2_in  + Q_sens_NH3_in);

Q_reactor_cooling = -(Q_rxn + Q_sensible_net);  % positive = heat to remove

%% ---- PRINT RESULTS -------------------------------------
fprintf('============================================\n');
fprintf('     REACTOR COOLING DUTY\n');
fprintf('============================================\n');
fprintf('Reactor conditions     : %.0f C, 200 bar\n', T_out - 273.15);
fprintf('NH3 produced           : %.4f kmol/day\n', nNH3_produced);
fprintf('\n');
fprintf('Reaction heat (Q_rxn)  : %.4E kJ/day\n', Q_rxn);
fprintf('                       = %.4f MW\n', Q_rxn/86400);
fprintf('\n');
fprintf('Sensible heat net      : %.4E kJ/day\n', Q_sensible_net);
fprintf('(zero if isothermal)   \n');
fprintf('\n');
fprintf('--------------------------------------------\n');
fprintf('TOTAL COOLING REQUIRED : %.4E kJ/day\n', Q_reactor_cooling);
fprintf('                       = %.4f MW\n', Q_reactor_cooling/86400);
fprintf('============================================\n');



%% ---- FUNCTION ------------------------------------------
function dH = H_change(T1, T2, A, B, C, D, R_val)
    H2 = A*T2 + B*T2^2/2 + C*T2^3/3 - D/T2;
    H1 = A*T1 + B*T1^2/2 + C*T1^3/3 - D/T1;
    dH = (H2 - H1) * R_val;
end